creds_ssh:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  transport: cli
  timeout: 60

creds_eapi:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  transport: eapi
  use_ssl: True
  validate_certs: no
