---
creds_core_nxapi:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  transport: nxapi
  use_ssl: yes
  validate_certs: no
  port: 8443
  timeout: 60
