--- 
- hosts: local
  vars:
    var1: hello
    var2: world
    my_dict:
        key1: zzzz
        key2: yyyy
        key3: whatever
    my_list:
        - hello
        - world
        - hello
        - world
        - hello
        - world
        - whatever
    my_list2:
        - world
        - 3
        - 77
        - Arista
    device: Cisco
        
  tasks:
    - name: Set operations
      debug:
        msg: "{{ my_list | unique }}"

    - name: Set operations (unique)
      debug:
        msg: "{{ my_list | unique }}"

    - name: Set operations (union)
      debug:
        msg: "{{ my_list | union(my_list2) }}"

    - name: Set operations (intersection)
      debug:
        msg: "{{ my_list | intersect(my_list2) }}"

    - name: Set operations, difference (unique items in my_list not in my_list2)
      debug:
        msg: "{{ my_list | difference(my_list2) }}"

    - name: Set operations, unique items in each list
      debug:
        msg: "{{ my_list | symmetric_difference(my_list2) }}"

