---
# Example using NX-API and NX-OS.
# Still requires a provider.
#
# To Execute:
# $ ansible-playbook nxos_facts.yml -i ./ansible-hosts
#
#
- name: Ansible2.5 NX-OS nxapi using provider
  gather_facts: no
  hosts: nxos 

  tasks:
    - name: NX-OS facts
      nxos_facts:
        provider: "{{ creds_core_nxapi }}"
