---
- name: Configuring Switchports
  hosts: pynet-sw6
  tasks:
    - name: Testing connectivity (Ansible Core)
      eos_facts:
        provider: "{{ creds_core_eapi }}"

    - name: Testing connectivity (NAPALM)
      napalm_get_facts:
        provider: "{{ creds_napalm }}"
