---

# Shows Ansible 2.5, no provider, using ansible_connection=netconf
#
# To Execute:
# $ ansible-playbook facts.yml -i ./ansible-hosts 
#
# Note, the password in ansible-hosts will need set correctly for the lab environment

- name: Ansible2.5 junos
  gather_facts: no
  hosts: juniper

  tasks:
    - name: Obtain junos facts
      junos_facts:
