---
- name: Generate BGP + VRF Configurations
  hosts: nxos
  tasks:
    - name: Generate BGP + VRF Configs
      template:
        src: vrf.j2
        dest: "./CFGS/{{ inventory_hostname }}-vrf.txt"

